### ISSUE TITLE
OOM when quantize DiT with the sieze of 512×512

### ISSUE THREAD

**Issue by vokkko** [adreamwu/PTQ4DiT#1]
Out of memory when i quantize the DiT with the size of 512×512 for one single 4090.
How can i use distribute gpu for quantization?

**Comment by adreamwu** [comment]
Thanks for your interest in our work.

The experiments were conducted on an RTX A6000 (48G). Our code does not support distributed training at the current stage.

Please refer to this [repo](https://github.com/YanjingLi0202/Q-ViT) for the implementation of multi-gpu training.

**Comment by vokkko** [comment]
Thank you for your reply.
