### ISSUE TITLE
why change "samples, _ = samples.chunk(2, dim=0)" into "samples = samples.chunk(2, dim=0)"

### ISSUE THREAD

**Issue by ningding-o** [adreamwu/PTQ4DiT#2]
https://github.com/adreamwu/PTQ4DiT/blob/c18734cfa80eb989af6e2fb9b3cf271186e5ea51/quant_sample.py#L221

Will this result in saving the null-class samples for the final FID score test ?

**Comment by adreamwu** [comment]
Hi, thank you for pointing this out. I have updated [quant_sample.py](https://github.com/adreamwu/PTQ4DiT/blob/main/quant_sample.py#L218-L222). Sorry for the confusion.
