### ISSUE TITLE
Unable to reproduce results with provided instructions

### ISSUE THREAD

**Issue by Juanerx** [adreamwu/PTQ4DiT#3]
Hi, thank you for the excellent work—it's been very insightful. However, after following the instructions exactly as provided without modifying any code, I am unable to reproduce the results.

First, I used the following command to generate the calibration dataset:
```bash
python get_calibration_set.py --model DiT-XL/2 --image-size 256 \
--ckpt pretrained_models/DiT-XL-2-256x256.pt \
--num-sampling-steps 50 \
--outdir outputs/ --filename imagenet_DiT-256_sample4000_50steps_allst.pt \
--cfg-scale 1.5 --seed 1
```

Then, I ran this command to generate 10,000 samples for evaluation:
```bash
python quant_sample.py --model DiT-XL/2 --image-size 256 \
--ckpt pretrained_models/DiT-XL-2-256x256.pt \
--num-sampling-steps 50 \
--weight_bit 4 --act_bit 8 --cali_st 25 --cali_n 64 --cali_batch_size 32 --sm_abit 8 \
--cali_data_path imagenet_DiT-256_sample4000_50steps_allst.pt --outdir outputs/ \
--cfg-scale 1.5 --seed 1 \
--ptq --recon \
--inference --n_c 10
```

Finally, I got the following evaluation metrics using ADM' suite:
Inception Score: 99.61454772949219
FID: 12.553096211451361
sFID: 22.030301594490652
Precision: 0.6439
Recall: 0.7007

However, the results I obtained do not match the expected values. Could you help identify what might be wrong with my steps or provide the checkpoint for the quantized model?

**Comment by Juanerx** [comment]
The settings is ImageNet 256x256, 50 timesteps and W4A8.

**Comment by adreamwu** [comment]
Hi,

Thank you for your interest. Could you please check if the code you are using is up to date?

**Comment by Juanerx** [comment]
Yes, it is up to date.

**Comment by adreamwu** [comment]
Hi. Please check our [checkpoint for the quantized model](https://drive.google.com/file/d/1ekdl32eISkrouVUBtuwZW8nTjhe4SF7X/view).
The setting is ImageNet 256x256, 50 timesteps, and W4A8.

Suppose we put the downloaded checkpoint at `output/256_48_50/ckpt.pth`. We can load this checkpoint and sample 10,000 images for evaluation:
```
python quant_sample.py --model DiT-XL/2 --image-size 256 \
--ckpt pretrained_models/DiT-XL-2-256x256.pt \
--num-sampling-steps 50 \
--weight_bit 4 --act_bit 8 --cali_st 25 --cali_n 64 --cali_batch_size 32 --sm_abit 8 \
--cali_data_path calib/imagenet_DiT-256_sample4000_50steps_allst.pt --outdir output/ \
--cfg-scale 1.5 --seed 1 \
--resume --cali_ckpt output/256_48_50/ckpt.pth \
--ptq \
--inference --n_c 10
```

We also provide the [.npz file of generated images](https://drive.google.com/file/d/1ID9o_CXxvMj3WYBLfL4QRXS2c3W3hio9/view) for reference.

The results we obtained in this experiment closely match those in the paper:
```
computing/reading sample batch statistics...
Computing evaluations...
Inception Score: 181.06820678710938
FID: 8.915899637239079
sFID: 23.01635424006895
Precision: 0.699
```

**Comment by Juanerx** [comment]
Thank you very much. This thoroughly addresses my concern.
